### ISSUE TITLE
is there a way to get a players grave back?

### ISSUE THREAD

**Issue by thighholder** [Just1Developer/MC_BetterGraves#1]
a player on my server teleported herself back into lava in the strongehold.. needless to say it glitched out and the head poofed, therefore everything burned. any way on me as an op grabbing a grave?

**Comment by Just1Developer** [comment]
Hey there!

As long as the grave *should* still be there (i.e. the save file is still there, gets deleted when collecting), you should be able to place and break a block at the graves location. 
The graves system does not pay attention to the block type in this case, just breaking a block at the graves' location should be enough to give her her stuff back.

However, when dying in lava the location is considered obstructed, so the grave might've been placed somewhere else. Getting the coordinates of the grave right is important here, I added a /gravelist command for that a few weeks ago, so she should be able to look up the coordinates there.

Hope this helps

**Comment by Just1Developer** [comment]
Hey!

Since I have already tested this and ensured that this _should_ work, and there as been no more activity, I'm going to mark this issue as resolved. If any further problems arise, feel free to [open up a new ticket](https://github.com/Just1Developer/MC_BetterGraves/issues/new) or write a message in the [plugin's discussion tab](https://www.spigotmc.org/threads/bettergraves.615142/) on spigot.

I wish you a merry christmas / happy holidays!
– JustOneDeveloper
