### ISSUE TITLE
Missing items after bugged grave spawn in water

### ISSUE THREAD

**Issue by NoneNamer** [Just1Developer/MC_BetterGraves#2]
One of my players, died in water and the head just popped and got collected by a drowned. After killing the imposter, and placing a block on the graves position he only got his exp back but the items were gone. Had to spawn him the items one by one, good thing i opened the grave file in vim before sugesting the block at the graves location.

Maybe place a dirt/glass block under the players head if there is water or add a command to manually restore a graves contents.

**Comment by Just1Developer** [comment]
Hey, pretty close to finishing that recover command, I also responded on Spigot yesterday. Since this is not the first time I'm told of this bug and I'm currently unable to recreate the bug, I'm interested in getting in touch with you to resolve this issue.
Feel free to add me on discord: justonedeveloper

**Comment by Just1Developer** [comment]
Hey, I'm gonna close this now due to inactivity. If the issue persists, feel free to dm me or reopen this ticket. 
Have a good one!
